[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["David Hotham <david.hotham@metaswitch.com>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
lazy_static = "1.4.0"
num = "0.3.1"
regex = "1"
structopt = "0.3.21"
